tap "bufbuild/buf"
tap "sunnyyoung/tap"

brew "aliyun-cli"
brew "ansible"
brew "bandwhich"
brew "bat"
brew "bottom"
brew "bufbuild/buf/buf"
brew "dust"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fisher"
brew "flarectl"
brew "fzf"
brew "gh"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "golangci-lint"
brew "jj"
brew "jq"
brew "lazygit"
brew "libpq"
brew "mas"
brew "mole"
brew "mosh"
brew "nexttrace"
brew "node"
brew "procs"
brew "ripgrep"
brew "sshpass"
brew "starship"
brew "sunnyyoung/tap/wechattweak"
brew "tmux"
brew "trash"
brew "uv"
brew "wakeonlan"
brew "wget"
brew "yazi"
brew "yt-dlp"
brew "zellij"
brew "zig"
brew "zoxide"

cask "1password"
cask "1password-cli"
cask "baidunetdisk"
cask "bitwarden"
cask "cherry-studio"
cask "clash-verge-rev"
cask "deskflow"
cask "discord"
cask "feishu"
cask "fork"
cask "futubull"
cask "futubull@legacy"
cask "ghostty"
cask "git-credential-manager"
cask "google-chrome"
cask "hex-fiend"
cask "iina"
cask "iterm2"
cask "jetbrains-toolbox"
cask "keka"
cask "logi-options+"
cask "longbridge-pro"
cask "monitorcontrol"
cask "notion"
cask "orbstack"
cask "qq"
cask "raycast"
cask "tailscale-app"
cask "telegram"
cask "tencent-lemon"
cask "tencent-meeting"
cask "thunder"
cask "typora"
cask "zed"

mas "Sequel Ace", id: 1518036000
mas "Xcode", id: 497799835
mas "Xnip", id: 1221250572
mas "同花顺", id: 1247341465

# Post-install:
# fisher install jhillyerd/plugin-git
# gh extension install drogers0/gh-image

# Maintenance:
# brew update && brew upgrade
# brew cleanup --prune=all && brew doctor
